name: A workflow for my Hello World file #This name appears on any pull request or in the Actions tab. 
on: push #indicates that your workflow will execute anytime code is pushed to your repository

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"